### ISSUE TITLE
Web API Authorization

### ISSUE THREAD

**Issue by ghost** [eduardolima93/angular2-spotify#7]
Hi there,

Are there any plans to include the "Client credentials flow" https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow Auth headers?

I'm unable to figure out how to provide an access token, and would like o make it possible to make simple calls without logging a user in.

Thanks for any advise on this.

Cheers!

**Comment by cnd5041** [comment]
@mmmmyers, is that possible? The Spotify docs say that the Client Credential flow must include a server side exchange.

**Comment by ghost** [comment]
Hi. Yep you're right.
I ended up using https://github.com/thelinmichael/spotify-web-api-node to get a token using the client credentials method and then subscribed to this from the client to create auth headers and pass the token to any Spotify calls.

**Comment by cnd5041** [comment]
@mmmmyers, Thanks, that could be really helpful. Really annoying to set up a backend just for that though 0_o
